### PR TITLE
Added Image component

### PR DESCRIPTION
**Pull request by sevfurneaux**
Added the React Native `Image` component.

However cannot replicate the API for adding the `uri` syntax:

`<Image source={{uri: movie.posters.thumbnail}} />`

`present(Image, {source: 'https://media4.giphy.com/media/ODy29v7YAJrck/200_s.gif'})`

### CODE REVIEW

**Comment by zetachang** [comment]
The reason is that the actual props passed to the element is a Ruby hash while the Image component expect it to be a plain JS object.

**Comment by sevfurneaux** [comment]
Thanks. So how would this be implemented?

**Comment by rainchen** [comment]
@sevfurneaux the solution is using `#to_n` method to convert the `Opal#Hash` object to `native_js#Hash` object , for example:
`present(Image, {source:  {uri: 'http://...'}.to_n}`

**Comment by sevfurneaux** [comment]
@rainchen Thanks!

**Pull request closed without merging**
